version: '3'

services:
  lesbar:
    build: server
    command: python main.py
    environment:
      FLASK_ENV: "development"
      SENTRY_DSN: "https://b2d8172ecb894f61a9a322788591c172@sentry.io/1540715"
    ports:
      - 8000:8000
    volumes:
      - ./server:/app

